class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'm'
        self.UnzipMirrorCommand = 'un'
        self.TarMirrorCommand = 'tar'
        self.ZipMirrorCommand = 'zip'
        self.CancelMirror = 'can'
        self.CancelAllCommand = 'canall'
        self.ListCommand = 'list'
        self.StatusCommand = 's'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'r'
        self.StatsCommand = 'stats'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'c'
        self.CountCommand = 'cn'
        self.WatchCommand = 'watch'
        self.TarWatchCommand = 'tarwatch'
        self.DeleteCommand = 'del'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'

BotCommands = _BotCommands()
